# Generated by Django 4.1.4 on 2022-12-08 07:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('token', models.CharField(
                    default=uuid.UUID('1c3555c2-860d-4910-91f1-70d734cb4580'),
                    editable=False,
                    max_length=255,
                    primary_key=True,
                    serialize=False
                )),
                ('lifetime', models.IntegerField(default=1440)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(
                    default=datetime.datetime(2022, 12, 8, 8, 21, 11, 193030, tzinfo=datetime.timezone.utc)
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
