# Generated by Django 4.1.4 on 2022-12-08 09:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtoken',
            name='token',
            field=models.CharField(default=uuid.UUID('7e60c155-0d1a-4970-8552-f248e6a42026'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 10, 1, 18, 362227, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='registrationtoken',
            table='user_registration_token',
        ),
    ]
