# Generated by Django 4.1.4 on 2022-12-08 11:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_registrationtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtoken',
            name='token',
            field=models.CharField(default=uuid.UUID('6c9446f7-2bbe-42be-9214-3a693e75365a'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 12, 22, 12, 397845, tzinfo=datetime.timezone.utc)),
        ),
    ]
